report_section_order:
  nms:
    after: "STAR alignment (genome)"
  "nf-core-clipseq-methods-description":
    order: -1001
  software_versions:
    order: -1002
  "clipseq-summary":
    order: -1003

export_plots: true

run_modules:
  - custom_content
  - fastqc
  - fastp
  - star
  - umitools

extra_fn_clean_exts:
  - ".umi_dedup"
  - "_val"
  - ".markdup"
  - ".nms.dedup"
  - ".nms"

custom_data:
  nms:
    file_format: "tsv"
    section_name: "NMS"
    description: "Non Maximum Suppression summary of the final alignment."
    plot_type: "bargraph"

module_order:
  - fastqc:
      name: "FastQC (raw)"
      # info: "This section of the report shows FastQC results before adapter trimming."
      path_filters:
        - "./fastqc/raw/*.zip"
  - fastp:
      path_filters:
        - "./fastp/*.fastp.json"
  - fastqc:
      name: "FastQC (trimmed)"
      # info: "This section of the report shows FastQC results after adapter trimming."
      path_filters:
        - "./fastqc/trim/*.zip"
  - star:
      name: "STAR alignment (RNA library)"
      # info: "This section reports STAR alignment metrics for the RNA collection."
      path_filters:
        - "./alignment/rnalib/*"
  - star:
      name: "STAR alignment (genome)"
      # info: "This section reports STAR alignment metrics to the whole genome."
      path_filters:
        - "./alignment/genome/*"
  - custom_content:
      path_filters:
        - "./alignment/nms/*_nms.tsv"
  - umitools:
      path_filters:
        - "./alignment/dedup/*.log"

# Customise the module search patterns to speed up execution time
#  - Skip module sub-tools that we are not interested in
#  - Replace file-content searching with filename pattern searching
#  - Don't add anything that is the same as the MultiQC default
# See https://multiqc.info/docs/#optimise-file-search-patterns for details
sp:
  nms:
    fn: "*_nms.tsv"
